blank_issues_enabled: false

contact_links:
  - name: GP Platform issues
    url: https://github.com/GraphicalPlayground/gp-platform/issues
    about: For bugs or feature requests related to the web platform (courses, cloud GPU execution, web UI), please open an issue on the gp-platform repository, not here.

  - name: Graphical Playground documentation repository
    url: https://github.com/GraphicalPlayground/gp-docs/issues
    about: Please report issues with documentation on the GP documentation repository, not here.

  - name: Graphical Playground community channels
    url: https://graphical-playground.com/community
    about: Please ask for technical support on one of the other community channels, not here.
